(function(){
  "use strict";
  const widget=document.getElementById("counselWidget");if(!widget)return;
  const launch=document.getElementById("counselLaunch"),panel=document.getElementById("counselPanel"),close=document.getElementById("counselClose");
  const tabs=widget.querySelectorAll("[data-counsel-tab]"),views=widget.querySelectorAll("[data-counsel-view]");
  const source=document.getElementById("refineSource"),result=document.getElementById("refineResult"),run=document.getElementById("refineRun"),copyResult=document.getElementById("refineCopy"),clearResult=document.getElementById("refineClear"),sourceCount=document.getElementById("refineSourceCount"),resultCount=document.getElementById("refineResultCount"),status=document.getElementById("refineStatus");
  const detectSource=document.getElementById("detectSource"),detectRun=document.getElementById("detectRun"),detectClear=document.getElementById("detectClear"),detectResults=document.getElementById("detectResults"),detectCount=document.getElementById("detectCount");
  let tone="friendly",detected={phones:[],orders:[]};
  function escapeHtml(value){return String(value==null?"":value).replace(/[&<>"']/g,function(char){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]})}
  function setOpen(open){widget.classList.toggle("is-open",open);launch.setAttribute("aria-expanded",String(open));panel.setAttribute("aria-hidden",String(!open));if(open){document.dispatchEvent(new CustomEvent("winco-popup-open",{detail:"counsel"}));setTimeout(function(){source.focus()},30)}}
  function activate(name){tabs.forEach(function(tab){tab.classList.toggle("is-active",tab.dataset.counselTab===name);tab.setAttribute("aria-selected",String(tab.dataset.counselTab===name))});views.forEach(function(view){view.classList.toggle("is-active",view.dataset.counselView===name)});setTimeout(function(){(name==="refine"?source:detectSource).focus()},20)}
  function updateCounts(){sourceCount.textContent=source.value.length.toLocaleString()+"자";resultCount.textContent=result.value.length.toLocaleString()+"자";detectCount.textContent=detectSource.value.length.toLocaleString()+"자"}
  function fallback(text,mode){let out=String(text||"").split(/\r?\n/).map(function(line){return line.trim()}).filter(function(line,index,lines){return line||lines[index-1]}).join("\n").replace(/\n{3,}/g,"\n\n").trim();if(mode==="concise")out=out.replace(/[ \t]+/g," ").replace(/\n{2,}/g,"\n");if((mode==="friendly"||mode==="apology")&&!/^안녕하세요/.test(out))out="안녕하세요, 고객님. 윈코입니다.\n\n"+out;if(mode==="apology"&&!/죄송|사과/.test(out))out=out.replace(/^(안녕하세요[^\n]*\n\n)?/,function(head){return(head||"")+"이용에 불편을 드려 죄송합니다.\n\n"});if(mode==="firm"&&!/^안내드립니다/.test(out))out="안내드립니다.\n\n"+out;if((mode==="friendly"||mode==="apology")&&!/감사합니다[.!]?$/.test(out))out+="\n\n감사합니다.";return out}
  async function refine(){const text=source.value.trim();if(!text){status.textContent="다듬을 문장을 입력해 주세요.";status.classList.add("is-error");source.focus();return}run.disabled=true;run.textContent="문장을 다듬는 중…";status.textContent="원문의 숫자와 업무 기준을 유지하며 정리하고 있습니다.";status.classList.remove("is-error");const controller=new AbortController(),timer=setTimeout(function(){controller.abort()},15000);try{const response=await fetch("/api/refine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:text,tone:tone}),signal:controller.signal});if(!response.ok)throw new Error("request failed");const data=await response.json();result.value=String(data.answer||"").trim()||fallback(text,tone);status.textContent="완료되었습니다. 결과를 직접 수정한 뒤 복사해도 됩니다."}catch(e){result.value=fallback(text,tone);status.textContent="빠른 기본 다듬기로 정리했습니다. 숫자와 내용을 한 번 확인해 주세요."}finally{clearTimeout(timer);run.disabled=false;run.textContent="고객 답변 다듬기";updateCounts();if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"detail",title:"고객 답변 문장 다듬기",detail:({friendly:"친절하게",concise:"짧게",firm:"명확하게",apology:"사과 포함"})[tone]})}}
  async function copyText(text,title){text=String(text||"").trim();if(!text)return;try{await navigator.clipboard.writeText(text)}catch(e){const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove()}if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"copy",title:title,detail:text})}
  function formatPhone(raw){let digits=raw.replace(/\D/g,"");if(digits.startsWith("82"))digits="0"+digits.slice(2);if(digits.length===11)return digits.replace(/(\d{3})(\d{4})(\d{4})/,"$1-$2-$3");if(digits.length===10){if(digits.startsWith("02"))return digits.replace(/(\d{2})(\d{4})(\d{4})/,"$1-$2-$3");return digits.replace(/(\d{3})(\d{3})(\d{4})/,"$1-$2-$3")}if(digits.length===9&&digits.startsWith("02"))return digits.replace(/(\d{2})(\d{3})(\d{4})/,"$1-$2-$3");return raw.trim()}
  function unique(list){return Array.from(new Set(list.filter(Boolean)))}
  function detect(){const text=detectSource.value;const phoneMatches=text.match(/(?<!\d)(?:\+?82[-.\s]?)?(?:0?1[016789]|0\d{1,2})[-.\s]?\d{3,4}[-.\s]?\d{4}(?!\d)/g)||[];const phones=unique(phoneMatches.map(formatPhone));const phoneDigits=new Set(phones.map(function(value){return value.replace(/\D/g,"")}));const orders=[];(text.match(/\bAS[-\s]?\d{8}[-\s]?\d{4}\b/gi)||[]).forEach(function(value){orders.push(value.toUpperCase().replace(/\s/g,"-").replace(/--+/g,"-"))});const named=/(?:주문|접수|오더|order)\s*(?:번호|no\.?|ID)?\s*[:#-]?\s*([A-Z0-9][A-Z0-9-]{5,29})/gi;let match;while((match=named.exec(text)))orders.push(match[1]);(text.match(/\b\d{14,20}\b/g)||[]).forEach(function(value){if(!phoneDigits.has(value))orders.push(value)});detected={phones:phones,orders:unique(orders)};renderDetected();if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"detail",title:"전화번호·주문번호 판독",detail:"전화번호 "+phones.length+"개 · 주문번호 "+detected.orders.length+"개"})}
  function section(title,type,items){if(!items.length)return"";return'<section class="detect-section"><div class="detect-section-head"><strong class="detect-section-title">'+title+'</strong><span class="detect-section-count">'+items.length+'개</span></div>'+items.map(function(value){return'<div class="detect-card"><span class="detect-type">'+(type==="phone"?"전화":"주문")+'</span><strong class="detect-value">'+escapeHtml(value)+'</strong><button class="detect-copy-one" type="button" data-detect-copy="'+escapeHtml(value)+'" aria-label="복사">복사</button></div>'}).join("")+'</section>'}
  function renderDetected(){if(!detected.phones.length&&!detected.orders.length){detectResults.innerHTML='<div class="detect-empty">찾은 전화번호나 주문번호가 없습니다.<br>번호가 포함된 상담 내용을 그대로 붙여 넣어 보세요.</div>';return}detectResults.innerHTML=section("전화번호","phone",detected.phones)+section("주문·접수번호","order",detected.orders)+'<button class="counsel-copy" id="detectCopyAll" type="button" style="width:100%;margin-top:10px;min-height:38px">찾은 정보 전체 복사</button>'}
  launch.addEventListener("click",function(){setOpen(true)});close.addEventListener("click",function(){setOpen(false)});tabs.forEach(function(tab){tab.addEventListener("click",function(){activate(tab.dataset.counselTab)})});widget.querySelectorAll("[data-tone]").forEach(function(button){button.addEventListener("click",function(){tone=button.dataset.tone;widget.querySelectorAll("[data-tone]").forEach(function(item){item.classList.toggle("is-active",item===button);item.setAttribute("aria-pressed",String(item===button))})})});source.addEventListener("input",updateCounts);result.addEventListener("input",updateCounts);detectSource.addEventListener("input",updateCounts);run.addEventListener("click",refine);copyResult.addEventListener("click",function(){copyText(result.value,"다듬은 고객 답변 복사")});clearResult.addEventListener("click",function(){source.value="";result.value="";status.textContent="";updateCounts();source.focus()});detectRun.addEventListener("click",detect);detectClear.addEventListener("click",function(){detectSource.value="";detected={phones:[],orders:[]};detectResults.innerHTML="";updateCounts();detectSource.focus()});detectResults.addEventListener("click",function(event){const button=event.target.closest("[data-detect-copy]");if(button){copyText(button.dataset.detectCopy,"판독 정보 복사");return}if(event.target.id==="detectCopyAll"){const text=(detected.phones.length?"[전화번호]\n"+detected.phones.join("\n"):"")+(detected.phones.length&&detected.orders.length?"\n\n":"")+(detected.orders.length?"[주문·접수번호]\n"+detected.orders.join("\n"):"");copyText(text,"판독 정보 전체 복사")}});document.addEventListener("winco-popup-open",function(event){if(event.detail!=="counsel")setOpen(false)});document.addEventListener("keydown",function(event){if(event.key==="Escape"&&widget.classList.contains("is-open"))setOpen(false)});updateCounts();
})();
