(function(root,factory){
  const parse=factory();
  if(typeof module!=="undefined"&&module.exports)module.exports=parse;
  if(root)root.wincoParseOrderInfo=parse;
})(typeof window!=="undefined"?window:null,function(){
  function unique(list){return Array.from(new Set(list.filter(Boolean)))}
  function formatPhone(raw){let digits=raw.replace(/\D/g,"");if(digits.startsWith("82"))digits="0"+digits.slice(2);if(digits.length===11)return digits.replace(/(\d{3})(\d{4})(\d{4})/,"$1-$2-$3");if(digits.length===10){if(digits.startsWith("02"))return digits.replace(/(\d{2})(\d{4})(\d{4})/,"$1-$2-$3");return digits.replace(/(\d{3})(\d{3})(\d{4})/,"$1-$2-$3")}if(digits.length===9&&digits.startsWith("02"))return digits.replace(/(\d{2})(\d{3})(\d{4})/,"$1-$2-$3");return raw.trim()}
  function extractProducts(text,commerceOrders,phones){const productLines=[],extras=[];let active=false;const phoneDigits=phones.map(function(value){return value.replace(/\D/g,"")});String(text||"").split(/\r?\n/).map(function(line){return line.trim()}).filter(Boolean).forEach(function(line){const found=commerceOrders.filter(function(order){return line.includes(order)});if(found.length){active=true;let tail=line;found.forEach(function(order){tail=tail.replace(order,"")});tail=tail.replace(/^[\s/|:·-]+/,"").trim();if(tail)productLines.push(tail);return}if(!active)return;const digits=line.replace(/\D/g,"");if(phoneDigits.some(function(phone){return phone&&digits.includes(phone)})||/^(수령인|주문자|구매자|고객명|연락처|전화번호|배송지|주소)\s*[:/]/.test(line)){active=false;return}const extra=line.match(/^추가선택\s*[:：]\s*(.+)$/);if(extra){extras.push(extra[1].trim());return}if(/^추가선택\s*$/.test(line))return;productLines.push(line)});return{products:productLines.length?[productLines.join("\n")]:[],extras:unique(extras)}}
  return function(text){text=String(text||"");const phoneMatches=text.match(/(?<!\d)(?:\+?82[-.\s]?)?(?:0?1[016789]|0\d{1,2})[-.\s]?\d{3,4}[-.\s]?\d{4}(?!\d)/g)||[];const phones=unique(phoneMatches.map(formatPhone));const phoneDigits=new Set(phones.map(function(value){return value.replace(/\D/g,"")}));const commerceOrders=unique(text.match(/\b\d{8}-\d{6,8}\b/g)||[]);const orders=commerceOrders.slice();(text.match(/\bAS[-\s]?\d{8}[-\s]?\d{4}\b/gi)||[]).forEach(function(value){orders.push(value.toUpperCase().replace(/\s/g,"-").replace(/--+/g,"-"))});const named=/(?:주문|접수|오더|order)\s*(?:번호|no\.?|ID)?\s*[:#-]?\s*([A-Z0-9][A-Z0-9-]{5,29})/gi;let match;while((match=named.exec(text)))orders.push(match[1]);(text.match(/\b\d{14,20}\b/g)||[]).forEach(function(value){if(!phoneDigits.has(value))orders.push(value)});const productData=extractProducts(text,commerceOrders,phones);return{phones:phones,orders:unique(orders),products:productData.products,extras:productData.extras}}
});
