(function(){
  "use strict";
  const widget=document.getElementById("counselWidget");if(!widget)return;
  const launch=document.getElementById("counselLaunch"),panel=document.getElementById("counselPanel"),close=document.getElementById("counselClose");
  const tabs=widget.querySelectorAll("[data-counsel-tab]"),views=widget.querySelectorAll("[data-counsel-view]");
  const source=document.getElementById("refineSource"),result=document.getElementById("refineResult"),run=document.getElementById("refineRun"),copyResult=document.getElementById("refineCopy"),clearResult=document.getElementById("refineClear"),sourceCount=document.getElementById("refineSourceCount"),resultCount=document.getElementById("refineResultCount"),status=document.getElementById("refineStatus");
  const detectSource=document.getElementById("detectSource"),detectRun=document.getElementById("detectRun"),detectClear=document.getElementById("detectClear"),detectResults=document.getElementById("detectResults"),detectCount=document.getElementById("detectCount");
  let tone="friendly",detected={phones:[],orders:[],products:[],extras:[]};
  function escapeHtml(value){return String(value==null?"":value).replace(/[&<>"']/g,function(char){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]})}
  function setOpen(open){widget.classList.toggle("is-open",open);launch.setAttribute("aria-expanded",String(open));panel.setAttribute("aria-hidden",String(!open));if(open){document.dispatchEvent(new CustomEvent("winco-popup-open",{detail:"counsel"}));setTimeout(function(){source.focus()},30)}}
  function activate(name){tabs.forEach(function(tab){tab.classList.toggle("is-active",tab.dataset.counselTab===name);tab.setAttribute("aria-selected",String(tab.dataset.counselTab===name))});views.forEach(function(view){view.classList.toggle("is-active",view.dataset.counselView===name)});setTimeout(function(){(name==="refine"?source:detectSource).focus()},20)}
  function updateCounts(){sourceCount.textContent=source.value.length.toLocaleString()+"자";resultCount.textContent=result.value.length.toLocaleString()+"자";detectCount.textContent=detectSource.value.length.toLocaleString()+"자"}
  function formatReply(text){let value=String(text||"").replace(/\r/g,"").trim();if(!value)return"";let lines=value.split(/\n+/).map(function(line){return line.replace(/\s+/g," ").trim()}).filter(Boolean);if(lines.length===1)lines=lines[0].split(/(?<=[.!?])\s+(?=[가-힣A-Za-z])/).filter(Boolean);if(lines.length>1&&/^안녕하세요/.test(lines[0])&&/^윈코입니다[.!]?$/.test(lines[1]))lines.splice(0,2,lines[0]+" "+lines[1]);return lines.join("\n")}
  function fallback(text,mode){return formatReply(typeof window.wincoRefineReply==="function"?window.wincoRefineReply(text,mode):String(text||""))}
  async function refine(){const text=source.value.trim();if(!text){status.textContent="메모나 고객에게 전달할 내용을 입력해 주세요.";status.classList.add("is-error");source.focus();return}run.disabled=true;run.textContent="완성 답변 작성 중…";status.textContent="입력 의도를 파악해 고객에게 바로 보낼 답변을 작성하고 있습니다.";status.classList.remove("is-error");const controller=new AbortController(),timer=setTimeout(function(){controller.abort()},28000);try{const response=await fetch("/api/refine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:text,tone:tone}),signal:controller.signal});if(!response.ok)throw new Error("request failed");const data=await response.json();result.value=formatReply(data.answer)||fallback(text,tone);status.textContent="완성된 답변입니다. 필요한 부분만 수정한 뒤 바로 복사할 수 있습니다."}catch(e){result.value=fallback(text,tone);status.textContent="입력 내용을 바탕으로 완성 답변을 작성했습니다. 숫자와 업무 기준만 확인해 주세요."}finally{clearTimeout(timer);run.disabled=false;run.textContent="완성 답변 작성하기";updateCounts();if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"detail",title:"고객 답변 문장 다듬기",detail:({friendly:"친절하게",concise:"짧게",firm:"명확하게",apology:"사과 포함"})[tone]})}}
  async function copyText(text,title){text=String(text||"").trim();if(!text)return;try{await navigator.clipboard.writeText(text)}catch(e){const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove()}if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"copy",title:title,detail:text})}
  function detect(){detected=window.wincoParseOrderInfo(detectSource.value);renderDetected();if(typeof window.wincoRecordActivity==="function")window.wincoRecordActivity({type:"detail",title:"주문·상품·전화번호 판독",detail:"주문번호 "+detected.orders.length+"개 · 상품 "+detected.products.length+"개 · 전화번호 "+detected.phones.length+"개"})}
  function section(title,type,items){if(!items.length)return"";const labels={phone:"전화",order:"주문",product:"상품",extra:"추가"},block=type==="product"||type==="extra";return'<section class="detect-section"><div class="detect-section-head"><strong class="detect-section-title">'+title+'</strong><span class="detect-section-count">'+items.length+'개</span></div>'+items.map(function(value){return'<div class="detect-card '+(block?'is-block':'')+'"><span class="detect-type">'+labels[type]+'</span><strong class="detect-value '+(block?'is-block':'')+'">'+escapeHtml(value)+'</strong><button class="detect-copy-one" type="button" data-detect-copy="'+escapeHtml(value)+'" aria-label="복사">복사</button></div>'}).join("")+'</section>'}
  function renderDetected(){if(!detected.phones.length&&!detected.orders.length&&!detected.products.length&&!detected.extras.length){detectResults.innerHTML='<div class="detect-empty">찾은 주문번호·상품 정보·전화번호가 없습니다.<br>주문 내용을 그대로 붙여 넣어 보세요.</div>';return}detectResults.innerHTML=section("주문·접수번호","order",detected.orders)+section("상품 정보","product",detected.products)+section("추가 선택","extra",detected.extras)+section("전화번호","phone",detected.phones)+'<button class="counsel-copy" id="detectCopyAll" type="button" style="width:100%;margin-top:10px;min-height:38px">분리한 정보 전체 복사</button>'}
  function detectedText(){return[{title:"주문·접수번호",items:detected.orders},{title:"상품 정보",items:detected.products},{title:"추가 선택",items:detected.extras},{title:"전화번호",items:detected.phones}].filter(function(group){return group.items.length}).map(function(group){return"["+group.title+"]\n"+group.items.join("\n")}).join("\n\n")}
  launch.addEventListener("click",function(){setOpen(true)});close.addEventListener("click",function(){setOpen(false)});tabs.forEach(function(tab){tab.addEventListener("click",function(){activate(tab.dataset.counselTab)})});widget.querySelectorAll("[data-tone]").forEach(function(button){button.addEventListener("click",function(){tone=button.dataset.tone;widget.querySelectorAll("[data-tone]").forEach(function(item){item.classList.toggle("is-active",item===button);item.setAttribute("aria-pressed",String(item===button))})})});source.addEventListener("input",updateCounts);result.addEventListener("input",updateCounts);detectSource.addEventListener("input",updateCounts);run.addEventListener("click",refine);copyResult.addEventListener("click",function(){copyText(result.value,"다듬은 고객 답변 복사")});clearResult.addEventListener("click",function(){source.value="";result.value="";status.textContent="";updateCounts();source.focus()});detectRun.addEventListener("click",detect);detectClear.addEventListener("click",function(){detectSource.value="";detected={phones:[],orders:[],products:[],extras:[]};detectResults.innerHTML="";updateCounts();detectSource.focus()});detectResults.addEventListener("click",function(event){const button=event.target.closest("[data-detect-copy]");if(button){copyText(button.dataset.detectCopy,"판독 정보 복사");return}if(event.target.id==="detectCopyAll")copyText(detectedText(),"판독 정보 전체 복사")});document.addEventListener("winco-popup-open",function(event){if(event.detail!=="counsel")setOpen(false)});document.addEventListener("keydown",function(event){if(event.key==="Escape"&&widget.classList.contains("is-open"))setOpen(false)});updateCounts();
})();
